  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:  
    name: "sf-auth"
    labels: 
      app: "sf-auth"
      track: "stable"
  spec: 
    replicas: 3
    template: 
      metadata: 
        name: "sf-auth"
        labels: 
          app: "sf-auth"
          track: "stable"
      spec: 
        containers: 
          - name: "sf-auth"
            image: "revature/sf-auth:0.1"
            ports: 
              - containerPort: 80
            resources:
              requests:
                cpu: 0.5
                memory: 800M
              limits:
                cpu: 0.5
                memory: 800M
            env:
              - name: "SF_AUTH_SERVER"
                valueFrom:
                  secretKeyRef:
                    name: "sf-auth-salesforce"
                    key: "sfAuthServer"
              - name: "CONSUMER_KEY"
                valueFrom:
                  secretKeyRef:
                    name: "sf-auth-salesforce"
                    key: "consumerKey"
              - name: "CONSUMER_SECRET"
                valueFrom:
                  secretKeyRef:
                    name: "sf-auth-salesforce"
                    key: "consumerSecret"
              - name: "CALLBACK_URL"
                valueFrom:
                  secretKeyRef:
                    name: "sf-auth-salesforce"
                    key: "callbackUrl"
#            livenessProbe:
#              httpGet:
#                path: /healthz
#                port: 8080
#              initialDelaySeconds: 20
#              timeoutSeconds: 5
#            readinessProbe:
#              httpGet:
#                path: /readiness
#                port: 8080
#              initialDelaySeconds: 40
#              timeoutSeconds: 5
